repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        stages: [commit]

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: migrations|settings.py
        args: # arguments to configure flake8
          - --max-line-length=88
        stages: [commit]

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
        name: isort (python)
        stages: [commit]
