# Generated by Django 4.1.4 on 2023-01-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_specialization_user_user_type_userprofile_patient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="sex",
            field=models.CharField(
                choices=[("M", "male"), ("F", "female")], default="M", max_length=1
            ),
        ),
    ]
