# Generated by Django 4.1.4 on 2023-01-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_admin_user_doctor_user_patient_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=255),
        ),
    ]
