# Generated by Django 4.1.4 on 2023-01-01 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="address",
        ),
    ]
