# Generated by Django 4.1.4 on 2023-01-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_admin_user_alter_doctor_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(
                choices=[("M", "male"), ("F", "female")], default="male", max_length=1
            ),
        ),
    ]
