# Generated by Django 4.1.4 on 2023-01-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
