# Generated by Django 4.1.4 on 2023-01-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
