# Generated by Django 4.1.4 on 2023-01-03 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="specialization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.specialization",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
