# Generated by Django 4.1.4 on 2023-01-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0003_alter_session_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="date",
            field=models.DateField(),
        ),
    ]
