# Generated by Django 4.1.4 on 2023-01-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0006_alter_appointment_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="is_valid",
        ),
    ]
